# Generated by Django 2.2 on 2022-05-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskupdate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='oid',
            field=models.CharField(default='O98CEAB6', editable=False, max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='products',
            name='pid',
            field=models.CharField(default='PC1D34', editable=False, max_length=6, primary_key=True, serialize=False),
        ),
    ]
